### DISCUSSION TITLE
Lima on termux

### DISCUSSION THREAD

**Discussion by wviana** [termux/termux-app#2738] [Q&A]
Hello. I'm trying to get Lima running on termux. 
I've opened [This discussion](https://github.com/lima-vm/lima/discussions/768#discussion-3973200) in Lima discussion but didn't get any answer. 
I've installed kind using prefix. It's in $PREFIX/bin. But when I try to run it I get a command not found. Even after cd into $PREFIX/bin and try ./limactl I get a no such a file or directory.

Any help on this?

**Comment by agnostic-apollo** [comment]
Binaries need to compiled for termux. Linux distros binaries mostly won't run on termux without patches.

https://github.com/termux/termux-packages/wiki/Building-packages

You would also require root to run `containerd`. I don't know whether lima will actually work on android as desired. Some root packages require custom kernels.

https://github.com/termux/termux-packages/tree/master/root-packages/containerd

**Reply by wviana** [reply]
Oh cool. Will try that. Actually Lima uses qemu, run containers inside guest. Will try to compile it and run. 

By the way, why do I get these erros instead of incompatible binary or something like that?

**Reply by agnostic-apollo** [reply]
Probably some missing library. Could use `strace` or something to find out.

https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists

**Reply by wviana** [reply]
Trying to compile got the follow after a bunch of git downloads. 

```
go: downloading gopkg.in/djherbis/times.v1 v1.2.0
mkdir -p _output/bin
cp -a ./cmd/nerdctl.lima _output/bin/nerdctl.lima
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w -X github.com/lima-vm/lima/pkg/version.Version=" -o _output/share/lima/lima-guestagent.Linux-x86_64 ./cmd/lima-guestagent
go: downloading github.com/elastic/go-libaudit/v2 v2.2.0
go: downloading github.com/yalue/native_endian v1.0.2
go: downloading github.com/pkg/errors v0.9.1
chmod 644 _output/share/lima/lima-guestagent.Linux-x86_64
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w -X github.com/lima-vm/lima/pkg/version.Version=" -o _output/share/lima/lima-guestagent.Linux-aarch64 ./cmd/lima-guestagent
chmod 644 _output/share/lima/lima-guestagent.Linux-aarch64
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp -aL examples _output/share/lima
cp: cannot create hard link '_output/share/lima/examples/ubuntu.yaml' to '_output/share/lima/examples/ubuntu-lts.yaml': Permission denied
make: *** [Makefile:26: binaries] Error 1
```
Looks like something about creating a hardlink. Will try to dig deeper.

**Reply by wviana** [reply]
This is the portion of Make file that triggers the `cp -aL`

```make
.PHONY: binaries
binaries: clean \
	_output/bin/lima \
	_output/bin/limactl \
	_output/bin/nerdctl.lima \
	_output/share/lima/lima-guestagent.Linux-x86_64 \
	_output/share/lima/lima-guestagent.Linux-aarch64
	cp -aL examples _output/share/lima
	mkdir -p _output/share/doc/lima
	cp -aL *.md LICENSE docs _output/share/doc/lima
	ln -sf ../../lima/examples _output/share/doc/lima
	echo $(VERSION) > _output/share/doc/lima/VERSION
```
What I've found about -L
```
-L, --dereference
              always follow symbolic links in SOURCE
```
Doesn't says anything about hardlink. Actually just about symbolic. Any tips about it?

**Reply by ghost** [reply]
cp `-a` argument may have caused it which preserves attributes and likely hardlinks was included or created. you could replace it with `-r`

**Reply by wviana** [reply]
> cp `-a` argument may have caused it which preserves attributes and likely hardlinks was included or created. you could replace it with `-r`

Thanks. For termux we make patches to add into repository right? If we achieve running it, have to add it into it patch. Will try without deleting the link later.

**Comment by wviana** [comment]
Ok, so I've unlinked a file from examples `unlink examples/ubuntu-lts.yaml` than I could run `make` without problem.
After it `make install`. 
Now I'm testing it. Tested alpine and got and error, now trying archlinux.
Will update later.

**Reply by wviana** [reply]
Got same error with archlinux.
Here is limactl start output:
```log
INFO[0000] Using the existing instance "alpine"         
WARN[0000] [hostagent] field `firmware.legacyBIOS` is not supported for architecture "aarch64", ignoring 
WARN[0000] [hostagent] failed to detect system DNS, falling back to [8.8.8.8 1.1.1.1] 
INFO[0000] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/data/data/com.termux/files/home/.lima/alpine/serial.log") 
INFO[0000] SSH Local Port: 40903                        
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0000] [hostagent] QEMU has exited                  
FATA[0000] exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/data/data/com.termux/files/home/.lima/alpine/ha.stderr.log"
```

Here is `ha.stderr.log` content:
```json
{"error":"no machine-id found, tried [/etc/machine-id /var/lib/dbus/machine-id]","level":"debug","msg":"failed to get machine ID, falling back to use hostname instead","time":"2022-04-26T03:39:08Z"}
{"level":"warning","msg":"field `firmware.legacyBIOS` is not supported for architecture \"aarch64\", ignoring","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"firmware candidates = [/data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd /usr/share/AAVMF/AAVMF_CODE.fd /usr/share/qemu-efi-aarch64/QEMU_EFI.fd]","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"OpenSSH version 9.0.1 detected","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2022-04-26T03:39:09Z"}
{"error":"open /etc/resolv.conf: no such file or directory","level":"warning","msg":"failed to detect system DNS, falling back to [8.8.8.8 1.1.1.1]","time":"2022-04-26T03:39:09Z"}
{"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/data/data/com.termux/files/home/.lima/archlinux/serial.log\")","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"qCmd.Args: [/data/data/com.termux/files/usr/bin/qemu-system-aarch64 -m 4096 -cpu host -machine virt,accel=tcg -smp 4,sockets=1,cores=4,threads=1 -drive if=pflash,format=raw,readonly=on,file=/data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd -boot order=c,splash-time=0,menu=on -drive file=/data/data/com.termux/files/home/.lima/archlinux/diffdisk,if=virtio -cdrom /data/data/com.termux/files/home/.lima/archlinux/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:38451-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:af:5b:fe -device virtio-rng-pci -display none -vga none -device ramfb -device qemu-xhci,id=usb-bus -device usb-kbd,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -parallel none -chardev socket,id=char-serial,path=/data/data/com.termux/files/home/.lima/archlinux/serial.sock,server=on,wait=off,logfile=/data/data/com.termux/files/home/.lima/archlinux/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/data/data/com.termux/files/home/.lima/archlinux/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-archlinux -pidfile /data/data/com.termux/files/home/.lima/archlinux/qemu.pid]","time":"2022-04-26T03:39:09Z"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /data/data/com.termux/files/usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/data/data/com.termux/files/home/.lima/_config/user\" -o IdentityFile=\"/data/data/com.termux/files/home/.ssh/mac_accedd\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=u0_a255 -o ControlMaster=auto -o ControlPath=\"/data/data/com.termux/files/home/.lima/archlinux/ssh.sock\" -o ControlPersist=5m -p 38451 127.0.0.1 -- /bin/bash]","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"qemu[stderr]: ","time":"2022-04-26T03:39:09Z"}
{"error":"exit status 1","level":"info","msg":"QEMU has exited","time":"2022-04-26T03:39:09Z"}
{"level":"debug","msg":"stdout=\"\", stderr=\"Connection reset by 127.0.0.1 port 38451\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"Connection reset by 127.0.0.1 port 38451\\r\\n\": exit status 255","time":"2022-04-26T03:39:09Z"}
```

**Reply by AkihiroSuda** [reply]
> Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes

Please try reducing the guest memory to below 3GiB

**Reply by wviana** [reply]
Ok. I did it. My config is
```yaml
images:
- location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.11/alpine-lima-std-3.15.4-x86_64.iso"
  arch: "x86_64"
  digest: "sha512:58b0003400aa5e54c54970a1a4d2376b3d3d6b48fffa5e21ea5b814f398920d6d38957f2a603520c03bdca178046915e198039243f296adf75ea380e02154aa5"
- location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.11/alpine-lima-std-3.15.4-aarch64.iso"
  arch: "aarch64"
  digest: "sha512:3449965ae57cef13e9af7797c064431bfee1a5132f5f4c181ff72ab19bacdc870d66dda44511a8214ba17e1d1f554bb34ebeb55da923290cf6598980c4077941"

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

firmware:
  legacyBIOS: true

cpu: 2
memory: 2GiB
disk: 1GiB

containerd:
  system: false
  user: false
```
Running  `limactl start alpine`

```log
time="2022-04-27T02:30:26Z" level=info msg="Using the existing instance \"alpine\""
time="2022-04-27T02:30:27Z" level=warning msg="[hostagent] field `firmware.legacyBIOS` is not supported for architecture \"aarch64\", ignoring"
time="2022-04-27T02:30:27Z" level=warning msg="[hostagent] failed to detect system DNS, falling back to [8.8.8.8 1.1.1.1]"
time="2022-04-27T02:30:27Z" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/data/data/com.termux/files/home/.lima/alpine/serial.log\")"
time="2022-04-27T02:30:27Z" level=info msg="SSH Local Port: 39519"
time="2022-04-27T02:30:27Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
time="2022-04-27T02:30:27Z" level=info msg="[hostagent] QEMU has exited"
time="2022-04-27T02:30:27Z" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/data/data/com.termux/files/home/.lima/alpine/ha.stderr.log\")"
```
`ha.stderr.log`: 

```json
{"error":"no machine-id found, tried [/etc/machine-id /var/lib/dbus/machine-id]","level":"debug","msg":"failed to get machine ID, falling back to use hostname instead","time":"2022-04-27T02:30:26Z"}
{"level":"warning","msg":"field `firmware.legacyBIOS` is not supported for architecture \"aarch64\", ignoring","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"firmware candidates = [/data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd /usr/share/AAVMF/AAVMF_CODE.fd /usr/share/qemu-efi-aarch64/QEMU_EFI.fd]","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"OpenSSH version 9.0.1 detected","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2022-04-27T02:30:27Z"}
{"error":"open /etc/resolv.conf: no such file or directory","level":"warning","msg":"failed to detect system DNS, falling back to [8.8.8.8 1.1.1.1]","time":"2022-04-27T02:30:27Z"}
{"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/data/data/com.termux/files/home/.lima/alpine/serial.log\")","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"qCmd.Args: [/data/data/com.termux/files/usr/bin/qemu-system-aarch64 -m 2048 -cpu host -machine virt,accel=tcg,highmem=off -smp 4,sockets=1,cores=4,threads=1 -drive if=pflash,format=raw,readonly=on,file=/data/data/com.termux/files/usr/share/qemu/edk2-aarch64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/data/data/com.termux/files/home/.lima/alpine/basedisk,media=cdrom,readonly=on -drive file=/data/data/com.termux/files/home/.lima/alpine/diffdisk,if=virtio -cdrom /data/data/com.termux/files/home/.lima/alpine/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:39519-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:fd:c9:a5 -device virtio-rng-pci -display none -vga none -device ramfb -device qemu-xhci,id=usb-bus -device usb-kbd,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -parallel none -chardev socket,id=char-serial,path=/data/data/com.termux/files/home/.lima/alpine/serial.sock,server=on,wait=off,logfile=/data/data/com.termux/files/home/.lima/alpine/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/data/data/com.termux/files/home/.lima/alpine/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-alpine -pidfile /data/data/com.termux/files/home/.lima/alpine/qemu.pid]","time":"2022-04-27T02:30:27Z"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /data/data/com.termux/files/usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/data/data/com.termux/files/home/.lima/_config/user\" -o IdentityFile=\"/data/data/com.termux/files/home/.ssh/mac_accedd\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=android -o ControlMaster=auto -o ControlPath=\"/data/data/com.termux/files/home/.lima/alpine/ssh.sock\" -o ControlPersist=5m -p 39519 127.0.0.1 -- /bin/bash]","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 39519: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 39519: Connection refused\\r\\n\": exit status 255","time":"2022-04-27T02:30:27Z"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: The 'host' CPU type can only be used with KVM or HVF","time":"2022-04-27T02:30:27Z"}
{"error":"exit status 1","level":"info","msg":"QEMU has exited","time":"2022-04-27T02:30:27Z"}
```

Any tips?

~sorry for posting a lot, I see it as a opportunity to document something and make it indexed by Google and others. May help someone or even me later. If I get into something I post updates~

**Reply by AkihiroSuda** [reply]
Is `runtime.GOOS` is set to "android" on termux?

Then you may have to modify this function to return "kvm" for "android"
https://github.com/lima-vm/lima/blob/c7034cee93ddbdeb36974c9831e86bf3cc42d7db/pkg/qemu/qemu.go#L540

**Reply by ghost** [reply]
For android it should return function to `tcg` instead regardless what arch is being used. because android doesn't have kvm acceleration support. least for now, btw i've noticed several things that are hardcoded to standard linux paths like `/etc/resolv.conf` and was attempting to use `host` cpu but `tcg` does not support it

**Reply by wviana** [reply]
> Is `runtime.GOOS` is set to "android" on termux?
> 
> Then you may have to modify this function to return "kvm" for "android" https://github.com/lima-vm/lima/blob/c7034cee93ddbdeb36974c9831e86bf3cc42d7db/pkg/qemu/qemu.go#L540

No I remember it was Linux when compiling. May try to change make script to better detect and set as android. But for now I'll probably just check if it works setting the variable, if get this is the reason I spend some time on improving make.

**Reply by wviana** [reply]
> For android it should return function to `tcg` instead regardless what arch is being used. because android doesn't have kvm acceleration support. least for now, btw i've noticed several things that are hardcoded to standard linux paths like `/etc/resolv.conf` 

This example like /etc/resolve.conf should be changed to something like $PREFIX right?

> and was attempting to use `host` cpu but `tcg` does not support it

Didn't get it? `tcg`?

**Reply by wviana** [reply]
How to you think performance will be? I know it will not be like I'm `kvm` but thought it may be ok cause it will be arm on arm.

**Reply by ghost** [reply]
> This example like /etc/resolve.conf should be changed to something like $PREFIX right?

Correct. you should be able to use `git grep` to find hardcoded paths and point it to prefix. optimal but some paths may not be necessary to change like macOS paths

> Didn't get it? tcg?

It was attempting to use it. maybe it's the root cause? 
```
{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: The 'host' CPU type can only be used with KVM or HVF","time":"2022-04-27T02:30:27Z"}
```
normally qemu will not use host cpu if tcg was used

> How to you think performance will be? I know it will not be like I'm kvm but thought it may be ok cause it will be arm on arm.

It would be slow. but using alpine maybe faster

**Reply by wviana** [reply]
> Is `runtime.GOOS` is set to "android" on termux?
> 
> Then you may have to modify this function to return "kvm" for "android" https://github.com/lima-vm/lima/blob/c7034cee93ddbdeb36974c9831e86bf3cc42d7db/pkg/qemu/qemu.go#L540

Hi there, long time after.
Trying again, tried to change this `case "linux"` to return `"android"`.

```
{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: The 'host' CPU type can only be used with KVM or HVF","time":"2022-05-12T01:01:27Z"}
```

Any other tips? 
will begin to dig it.

**Reply by ghost** [reply]
Try negating this condition to `if ! IsNativeArch(arch)`
https://github.com/lima-vm/lima/blob/234a65c761d0f5c4efe5be14902aac0ca51797ce/pkg/limayaml/defaults.go#L108

**Reply by wviana** [reply]
OMG, it finally worked. 
Just able to run shell on alpine. Maybe try some docker tomorrow.
So close for docker in usermode in Android. :smile: 

Too late now, tomorrow I report how I did progress.

**Reply by wviana** [reply]
> Try negating this condition to `if ! IsNativeArch(arch)` https://github.com/lima-vm/lima/blob/234a65c761d0f5c4efe5be14902aac0ca51797ce/pkg/limayaml/defaults.go#L108

I actually commented out that entire loop testing Arch.
Just to make it work for now. Later will try to understand and find out why do they need that and how to add to handle this termux scenario.

**Comment by luisdavim** [comment]
@wviana have you tryed using an imge for `aarch64` or `arm64v8` instead of `x86_64`?

**Reply by wviana** [reply]
Hey @luisdavim ,
How are you doing?
There is a long time I didn't tried it anymore.
Will try again later, reply with news later.

**Reply by wviana** [reply]
Ok, so I was able to run alpine local. These are the changes I made to achieve it:
```patch
diff --git a/Makefile b/Makefile
index 26fc6f4..31c29ef 100644
--- a/Makefile
+++ b/Makefile
@@ -24,9 +24,9 @@ binaries: clean \
 	_output/share/lima/lima-guestagent.Linux-x86_64 \
 	_output/share/lima/lima-guestagent.Linux-aarch64 \
 	_output/share/lima/lima-guestagent.Linux-riscv64
-	cp -aL examples _output/share/lima
+	cp -rL examples _output/share/lima
 	mkdir -p _output/share/doc/lima
-	cp -aL *.md LICENSE docs _output/share/doc/lima
+	cp -rL *.md LICENSE docs _output/share/doc/lima
 	ln -sf ../../lima/examples _output/share/doc/lima
 	echo $(VERSION) > _output/share/doc/lima/VERSION
 
diff --git a/examples/alpine.yaml b/examples/alpine.yaml
index ca5d0ad..d731df5 100644
--- a/examples/alpine.yaml
+++ b/examples/alpine.yaml
@@ -7,9 +7,13 @@ images:
   arch: "aarch64"
   digest: "sha512:3449965ae57cef13e9af7797c064431bfee1a5132f5f4c181ff72ab19bacdc870d66dda44511a8214ba17e1d1f554bb34ebeb55da923290cf6598980c4077941"
 
+cpus: 1
+memory: 1GiB
+disk: 2GiB
+
 mounts:
 - location: "~"
-- location: "/tmp/lima"
+- location: "~/tmp/lima"
   writable: true
 
 firmware:
diff --git a/pkg/limayaml/defaults.go b/pkg/limayaml/defaults.go
index beeb7b4..9bf6ee9 100644
--- a/pkg/limayaml/defaults.go
+++ b/pkg/limayaml/defaults.go
@@ -104,11 +104,12 @@ func FillDefault(y, d, o *LimaYAML, filePath string) {
 		X8664:   "qemu64",
 		RISCV64: "rv64", // FIXME: what is the right choice for riscv64?
 	}
-	for arch := range cpuType {
+	/* for arch := range cpuType {
 		if IsNativeArch(arch) {
 			cpuType[arch] = "host"
 		}
-	}
+	} */
+	logrus.Warnf("cpuType %s", cpuType)
 	for k, v := range d.CPUType {
 		if len(v) > 0 {
 			cpuType[k] = v
@@ -587,6 +588,7 @@ func ResolveArch(s *string) Arch {
 }
 
 func IsNativeArch(arch Arch) bool {
+	logrus.Warnf("Arch %s GOARCH %s", arch, runtime.GOARCH)
 	nativeX8664 := arch == X8664 && runtime.GOARCH == "amd64"
 	nativeAARCH64 := arch == AARCH64 && runtime.GOARCH == "arm64"
 	nativeRISCV64 := arch == RISCV64 && runtime.GOARCH == "riscv64"
```

to build: 

- make
-  make install
- limactl start ./examples/alpine.yaml

**Reply by wviana** [reply]
Trying to run examples/docker.yaml

```
WARN[0006] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
WARN[0006] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
WARN[0006] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
INFO[0006] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-arm64.img"  digest="sha256:66224c7fed99ff5a5539eda406c87bbfefe8af6ff6b47d92df3187832b5b5d4f"
INFO[0007] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"  digest=
580.69 MiB / 580.69 MiB [-----------------------------------] 100.00% 7.38 MiB/s
INFO[0088] Downloaded the image from "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img" 
WARN[0088] [hostagent] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
WARN[0088] [hostagent] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
WARN[0088] [hostagent] Arch aarch64 GOARCH arm64        
WARN[0088] [hostagent] failed to detect system DNS, falling back to [8.8.8.8 1.1.1.1] 
INFO[0088] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/data/data/com.termux/files/home/.lima/docker/serial.log") 
INFO[0088] SSH Local Port: 40279                        
INFO[0088] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0098] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0184] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0269] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0354] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0406] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0416] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0426] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0436] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0446] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0456] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0466] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0476] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0486] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0496] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0506] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0516] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0526] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0536] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0546] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0556] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0566] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0576] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0586] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0596] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0606] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0616] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0626] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0636] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0672] [hostagent] The essential requirement 1 of 5 is satisfied 
INFO[0672] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
FATA[0688] did not receive an event with the "running" status
```

Even after it stop. Looks like it qemu is running, as this is the output for `limactl ls`

```
ARN[0000] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
WARN[0000] cpuType map[aarch64:cortex-a72 riscv64:rv64 x86_64:qemu64] 
NAME      STATUS     SSH                ARCH       CPUS    MEMORY    DISK      DIR
alpine    Stopped    127.0.0.1:0        aarch64    1       1GiB      2GiB      /data/data/com.termux/files/home/.lima/alpine
docker    Running    127.0.0.1:40279    aarch64    4       4GiB      100GiB    /data/data/com.termux/files/home/.lima/docker
```

I can shell into the docker machine, is there something I could do to test why I got that error?

**Reply by lars18th** [reply]
Hi @wviana ,

Any advance with Lima on Termux?

I'm interested on this option. The main reason is because Lima is based on UML (User-Mode-Linux). Therefore it will be interesting if we can run a pseudo-kernel in our Android Termux ARM environment without root support.

**Reply by sylirre** [reply]
UML Linux is available only for x86(64) devices and does not work without SysV IPC.

On ARM Lima can work through QEMU.

**Reply by AkihiroSuda** [reply]
Lima is irrelevant to UML.

**Comment by Shareed2k** [comment]
just compile it in termux build env like this 
```sh
TERMUX_PKG_HOMEPAGE=https://github.com/lima-vm/lima
TERMUX_PKG_DESCRIPTION="Linux virtual machines, with a focus on running containers"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.20.1"
TERMUX_PKG_SRCURL=https://github.com/lima-vm/lima/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=3e8b16572a23d69ad16ef72f15b1697c35b5eacaf6c1f0943b6ebfb8bfaf1fd7
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_make() {
	termux_setup_golang
	export GOPATH=$TERMUX_PKG_CACHEDIR/go

	make binaries
}

termux_step_make_install() {
	install -Dm700 -t $TERMUX_PREFIX/bin $TERMUX_PKG_SRCDIR/_output/bin/*
	install -Dm700 -t $TERMUX_PREFIX/bin $TERMUX_PKG_SRCDIR/_output/share/lima/lima-guestagent.Linux-aarch64
}
```

you will get deb file in `output/` dir like this one `lima-vm_0.20.1_aarch64.deb` install it in termux and run with this example
also you need to install `qemu-system-x86-64-headless`  this is already include `qemu-system-aarch64-headless` and `qemu-img`

```yaml
# This template requires Lima v0.7.0 or later.
# Using the Alpine 3.19 aarch64 image with vmType=vz requires macOS Ventura 13.3 or later.

images:
- location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.37/alpine-lima-rd-3.19.0-aarch64.iso"
  arch: "aarch64"
  digest: "sha512:8e41de22f9b3f6fc26df70ce8cce1b7698b0eb3fb13071c47965518472875270705a1a45bac0d22ad0ea6338a82e9e4c5cdbbef51df4aba08bedcdae30baa3a0"

mounts:
- location: "~"
  writable: true
- location: "~/tmp/lima"
  writable: true

# The built-in containerd installer does not support Alpine currently.
# Hint: use the "rd" ISO instead of the "std" ISO to enable containerd: https://github.com/lima-vm/alpine-lima/releases/
containerd:
  system: false
  user: false
provision:
- mode: system
  # This script defines the host.docker.internal hostname when hostResolver is disabled.
  # It is also needed for lima 0.8.2 and earlier, which does not support hostResolver.hosts.
  # Names defined in /etc/hosts inside the VM are not resolved inside containers when
  # using the hostResolver; use hostResolver.hosts instead (requires lima 0.8.3 or later).
  script: |
    #!/bin/sh
    sed -i 's/host.lima.internal.*/host.lima.internal host.docker.internal/' /etc/hosts
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    addgroup {{.User}} docker
    rc-update add docker default
    service docker start
- script: |
    #!/bin/bash
    set -eux -o pipefail
    if ! timeout 30s bash -c "until command -v docker >/dev/null 2>&1; do sleep 3; done"; then
      echo >&2 "docker is not installed yet"
      exit 1
    fi
    if ! timeout 30s bash -c "until pgrep dockerd; do sleep 3; done"; then
      echo >&2 "dockerd is not running"
      exit 1
    fi
  hint: See "/var/log/cloud-init-output.log". in the guest
hostResolver:
  # hostResolver.hosts requires lima 0.8.3 or later. Names defined here will also
  # resolve inside containers, and not just inside the VM itself.
  hosts:
    host.docker.internal: host.lima.internal
portForwards:
- guestSocket: "/var/run/docker.sock"
  hostSocket: "{{.Dir}}/sock/docker.sock"
message: |
  To run `docker` on the host (assumes docker-cli is installed), run the following commands:
  ------
  docker context create lima-{{.Name}} --docker "host=unix://{{.Dir}}/sock/docker.sock"
  docker context use lima-{{.Name}}
  docker run hello-world
  ------
```
