### DISCUSSION TITLE
How can i run termux from docker in  CI/CD

### DISCUSSION THREAD

**Discussion by John4650-hub** [termux/termux-app#4291] [Q&A] [answered]
how can i run the termux-docker image in something like github actions or circleci.
I have tried but in both cases i get incompatibility issues. 

I am working on a project in which i need to install alot of packages from the termux repo, and my device is kinda running short of storage space, so only option is this.
The files in the project are mainly C++ files, and a few in Rust.
Is it possible to build a custom the image with the required packages installed such that i save time when compiling.

**Comment by twaik** [comment]
https://github.com/termux/termux-packages/blob/master/.github/workflows/packages.yml
https://github.com/termux-user-repository/tur/blob/master/.github/workflows/packages.yml

**Reply by twaik** [reply]
It is https://github.com/termux-user-repository/tur/blob/master/.github/workflows/package_on_device.yml in the case if you mean termux-only docker image used for testing and not the termux-package-builder image.

**Reply by John4650-hub** [reply]
l want to use `arm` for this 
This seems to be what i need. I have read through but I am unable to find a way to implement what i want to do, 
Could you give me an example of how i could do the following:
run a command with in the termux image like `pkg install clang` .
Thanks for the help

**Reply by John4650-hub** [reply]
Is there a way to also build the termux-only docker image using a Dockerfile with the the packages i need for my project installed. So that i just pull from dockerhub and use in my other worflows.

**Reply by twaik** [reply]
See the https://github.com/termux/termux-docker repo.

**Reply by John4650-hub** [reply]
@twaik, I am having issues here's the output
```bash
Run docker run --rm termux/termux-docker:arm bash -c "apt update && apt install -yq clang"
Unable to find image 'termux/termux-docker:arm' locally
arm: Pulling from termux/termux-docker
91c7778f5181: Pulling fs layer
4f4fb700ef54: Pulling fs layer
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
91c7778f5181: Verifying Checksum
91c7778f5181: Download complete
91c7778f5181: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:73283f38880599da4e9bd80821a831a545e664dafb38ca5550061d83c2ad04a8
Status: Downloaded newer image for termux/termux-docker:arm
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /entrypoint.sh: exec format error
```

**Reply by twaik** [reply, marked as answer]
You did not setup binfmt misc...

**Reply by Biswa96** [reply]
Please read the README file in the termux-docker project. "If architecture is not compatible with host, the additional setup will be needed. Read this document further to learn how you can run containers of incompatible CPU architecture."

**Reply by John4650-hub** [reply]
The container started but the following information was displayed
```bash
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
error getting old personality value: Operation not permitted
libc: error getting old personality value: Operation not permitted
Aborted (core dumped)
[!] Container is running as non-root, unable to start dnsmasq. DNS will be unavailable.
error getting old personality value: Operation not permitted
libc: error getting old personality value: Operation not permitted
```
The `Run Termux` step won't proceed as the container doesn't stop.
This how the workflow step looks like
```yaml
- name: Run Termux
      run: |
        docker run --rm --privileged aptman/qus -s -- -p aarch64 arm
        docker run --rm termux/termux-docker:arm bash -c "apt update && apt install -yq clang && clang -help > foo.txt"
        docker ps -q | xargs -r docker stop

    - name: Show foo
      run: cat foo.txt
```

**Reply by robertkirkman** [reply]
@John4650-hub Sorry, I didn't see this message before now,

Over the course of 2025, I have spent a large amount of time studying termux-docker, so thankfully, I believe that I have a mostly complete understanding of all of these termux-docker errors that you have encountered and I also know potential solutions to them:

- `unable to start dnsmasq. DNS will be unavailable`
- `error getting old personality value: Operation not permitted`
- `The requested image's platform does not match the detected host platform`
- `/entrypoint.sh: exec format error`
- `Aborted (core dumped)`
- `cannot locate symbol "_ZNSt6__ndk122__libcpp_verbose_abortEPKcz" referenced by "/data/data/com.termux/files/usr/bin/clang-19".`
- other "incompatibility issues"
- termux-docker inside GitHub Actions

Some of these problems are currently possible to work around without rebuilding the termux-docker image, by setting up termux-docker differently, including changing GitHub-Actions-related settings if using termux-docker inside GitHub Actions, so the current official termux-docker image might be sufficient depending on what you need to do overall,

however, unfortunately, depending on the specific configuration and use-cases of termux-docker you need, fixing some of the problems currently requires using the new branch of termux-docker that I have created, which has many bugs fixed compared to the current official termux-docker image.

Here are links to the relevant termux-docker resources I have created, which contain additional documentation about these topics:

- Information about how to use termux-docker inside GitHub Actions: https://github.com/termux/termux-docker/issues/62
  - One of my examples of correctly using termux-docker inside GitHub Actions: https://github.com/robertkirkman/termux-on-gha/blob/master/.github/workflows/build-and-test.yml
  - One of my more specialized examples: https://github.com/owokitty/termux-on-gha/blob/master/.github/workflows/build-and-test.yml
- The error **`error getting old personality value: Operation not permitted`** has **multiple potential causes, but unfortunately, my testing has determined that _slight emulation inaccuracies present in the `binfmt_misc` emulation method can cause it_, while another emulation method is unaffected by the problem**. Here is a script I have written that builds and launches a **custom termux-docker ARM emulator** based on custom builds of QEMU and OpenSSH that I have very carefully written and tested _specifically_ to prevent **all** known possible causes of the error `error getting old personality value: Operation not permitted` while using termux-docker ARM on an x86 computer.
  -  https://gist.github.com/robertkirkman/f79441c79811ad263f2f881f7864e793#file-install-termux-docker-inside-qemu-full-system-emulator-sh
  - If you still need to use an ARM image of termux-docker on an x86 computer, but continue to struggle with the `error getting old personality value: Operation not permitted` error or similar errors mentioning "`personality`", then you can try using my custom termux-docker emulator, which, while slower, is **more accurate than `binfmt_misc`** and is _not_ affected by any "`personality`" errors.
  - If GitHub Actions is still the place where you need to run termux-docker, then rather than using emulation, I **strongly** suggest following my example of using the new GitHub Actions ARM runners to run the termux-docker ARM images instead, which run termux-docker's ARM image on real ARM cloud hardware, very efficiently, without the need for any emulators.

- My new branch of termux-docker: https://github.com/termux/termux-docker/pull/72

If you still would like to try to use termux-docker, please let me know, and especially if you are able to do so, you can show me the code of the project that you need to build or run inside termux-docker inside GitHub Actions, and I might be able to help you do that.

**Comment by John4650-hub** [comment]
This worked
```yaml
name: Set up QEMU for aarch64 emulation
      run: docker run --rm --privileged aptman/qus -s -- -p aarch64 arm

    - name: Run Termux
      run: |
        docker run \
          --privileged \
          --name termux-docker-arm \
          termux/termux-docker:arm \
          bash -c "uname -a" > /home/runner/work/learn-docker/learn-docker/foo.txt
        docker stop termux-docker-arm

    - name: Cleanup Docker
      if: always()
      run: |
        docker ps -aq --filter "name=termux-arm" | xargs -r docker stop
        docker ps -aq --filter "name=termux-arm" | xargs -r docker rm
    - run: cat foo.txt
```
