### ISSUE TITLE
Add FUNDING.yml

### ISSUE THREAD

**Issue by NatoBoram** [termux/termux-app#1824]
I think it would be a nice idea to increase the visibility of funding options using GitHub's integration.

> [**Displaying a sponsor button in your repository**](https://docs.github.com/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)  
> You can add a sponsor button in your repository to increase the visibility of funding options for your open source project.  

Example : 

```yaml
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: termux # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://termux.com/donate', 'https://paypal.me/fornwall'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
```
